### ISSUE TITLE
エラーメッセージを出ました

### ISSUE THREAD

**Issue by marco2632** [proshunsuke/colmsg#59]
使用の際にこのメッセージを出ました
僕は普通に使用したけど
`[31m[colmsg error][0m: HTTP status client error (400 Bad Request) for url (https://api.kh.glastonr.net/v2/update_token)`

**Comment by marco2632** [comment]
maybe i use english would be better for you to understand. i want to ask about do this need me always set the mitmproxy on or i can delete it after i get the token? it not then i think the problem is that i delete the mitmproxy right after getting token.

**Comment by marco2632** [comment]
The same error happen when i insert the token to the program
but it is a little bit difference is that i can save sakura before the error and i cannot save hinata 
> [31m[colmsg error][0m: HTTP status client error (400 Bad Request) for url (https://api.s46.glastonr.net/v2/update_token)

> [31m[colmsg error][0m: HTTP status client error (400 Bad Request) for url (https://api.kh.glastonr.net/v2/update_token)

**Comment by proshunsuke** [comment]
When a token is deleted, the previously used token is no longer available. For example, if you launch the app on a different device and log in, your old token will be deleted and you will not be able to use it. The same thing happens when you use an emulator such as Genymotion.
The token you get by using mitmproxy can be used as long as it is not deleted.

**Comment by marco2632** [comment]
I used mitmproxy twice, once for sakura and once for hinata. After i got the token, i only used the apps on the same device and run the program in my computer. but i still cannot do anything.
But anyway i will get the token one more time, hope i can use it. Thank you

**Comment by proshunsuke** [comment]
There seems to be no problem, so close this issue.
